### ISSUE TITLE
Can't use the name 'strategy' for a relationship in a RelatedFactory

### ISSUE THREAD

**Issue by jwg4** [rbarrois/factory_boy#227]
The following minimal example (for SQLAlchemy)

``` python
import unittest
from sqlalchemy import Column, Integer, ForeignKey, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import scoped_session, sessionmaker, relationship
import factory 
from factory.alchemy import SQLAlchemyModelFactory

engine = create_engine('sqlite://')
session = scoped_session(sessionmaker(bind=engine))
Base = declarative_base()

# Change this to anything except 'strategy' for the test to pass:
BACKREF_NAME = 'strategy'

class Bar(Base):
    __tablename__ = 'BarTable'

    id = Column(Integer(), primary_key=True)
    strategy_id = Column(Integer(), ForeignKey('StrategyTable.id'))

class Strategy(Base):
    __tablename__ = 'StrategyTable'

    id = Column(Integer(), primary_key=True)
    bars = relationship('Bar', backref=BACKREF_NAME)

class BarFactory(SQLAlchemyModelFactory):
    class Meta:
        model = Bar
        sqlalchemy_session = session

    id = factory.Sequence(lambda n: n)

class StrategyFactory(SQLAlchemyModelFactory):
    class Meta:
        model = Strategy
        sqlalchemy_session = session

    id = factory.Sequence(lambda n: n)
    bar1 = factory.RelatedFactory(BarFactory,BACKREF_NAME)

class TestFoo(unittest.TestCase):
    def setUp(self):
        self.strategy = StrategyFactory()

    def test_can_create_foo(self):
        self.assertIsNotNone(self.strategy)
```

fails with the error:
```
======================================================================
ERROR: test_can_create_foo (test_factory.TestFoo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/z/test_factory.py", line 44, in setUp
    self.strategy = StrategyFactory()
  File "/home/jack/z/venv/local/lib/python2.7/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/home/jack/z/venv/local/lib/python2.7/site-packages/factory/base.py", line 559, in create
    return cls._generate(True, attrs)
  File "/home/jack/z/venv/local/lib/python2.7/site-packages/factory/base.py", line 490, in _generate
    results[name] = decl.call(obj, create, extraction_context)
  File "/home/jack/z/venv/local/lib/python2.7/site-packages/factory/declarations.py", line 535, in call
    return factory.simple_generate(create, **passed_kwargs)
  File "/home/jack/z/venv/local/lib/python2.7/site-packages/factory/base.py", line 645, in simple_generate
    return cls.generate(strategy, **kwargs)
TypeError: generate() got multiple values for keyword argument 'strategy'

----------------------------------------------------------------------
```

Changing the name of the relationship (in the constant `BACKREF_NAME` for convenience) to anything else, makes it work. What seems to happen is that when the Bar object is created as a related object, the argument `strategy` is passed in, equal to the newly created Strategy object. This conflicts with the argument `strategy` which is used by factory_boy, which is set to `CREATE_STRATEGY` or `BUILD_STRATEGY`.

We have a model called 'strategy' with foreign keys like the above in our real code, and it would be a pain for us to change these models. Could the way the code works be changed, or are there any workarounds?

Thanks in advance.

**Comment by jeffwidman** [comment]
Have you tried using [`rename`](http://factoryboy.readthedocs.org/en/latest/reference.html?highlight=rename#factory.FactoryOptions.rename)?

Not sure that it will fix it since this is a `RelatedFactory` definition, not a typical factory attribute. But it's worth checking.
