### ISSUE TITLE
Cannot run tests locally, `No module named 'flask'`

### ISSUE THREAD

**Issue by jamesbeith** [rbarrois/factory_boy#238]
Using the current latest commit 197555d3d0de4759ca9ad45d5986fdcc4aa4c15b, a fresh virtualenv with Python 3.4.2 and running `make DJANGO=1.8 test` I get the following error: `No module named 'flask'`

```
(factory_boy)James-MacBook-Pro-Personal:factory_boy James$ make DJANGO=1.8 test
pip install --upgrade pip setuptools
You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Using cached pip-7.1.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached setuptools-18.4-py2.py3-none-any.whl
Installing collected packages: pip, setuptools
  Found existing installation: pip 6.1.1
    Uninstalling pip-6.1.1:
      Successfully uninstalled pip-6.1.1
  Found existing installation: setuptools 15.0
    Uninstalling setuptools-15.0:
      Successfully uninstalled setuptools-15.0
Successfully installed pip-7.1.2 setuptools-18.4
pip install --upgrade -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt
Collecting coverage (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 1))
  Using cached coverage-4.0.1.tar.gz
Collecting Pillow (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 2))
  Using cached Pillow-3.0.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting mock (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 3))
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting wheel (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 4))
  Using cached wheel-0.26.0-py2.py3-none-any.whl
Collecting fake-factory>=0.5.0 (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 5))
  Using cached fake-factory-0.5.3.tar.gz
Collecting Django<1.9,>=1.8 (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 6))
  Using cached Django-1.8.5-py2.py3-none-any.whl
Collecting SQLAlchemy<1.1,>=1.0 (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 7))
  Using cached SQLAlchemy-1.0.8.tar.gz
Collecting mongoengine<0.10,>=0.9 (from -r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 8))
  Using cached mongoengine-0.9.0.tar.gz
Collecting six>=1.7 (from mock->-r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->-r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 3))
  Using cached pbr-1.8.1-py2.py3-none-any.whl
Collecting pymongo>=2.7.1 (from mongoengine<0.10,>=0.9->-r auto_dev_requirements_django1.8_alchemy1.0_mongoengine0.9.txt (line 8))
  Using cached pymongo-3.0.3-cp34-cp34m-macosx_10_6_intel.whl
Installing collected packages: coverage, Pillow, six, pbr, mock, wheel, fake-factory, Django, SQLAlchemy, pymongo, mongoengine
  Running setup.py install for coverage
  Running setup.py install for fake-factory
  Running setup.py install for SQLAlchemy
  Running setup.py install for mongoengine
Successfully installed Django-1.8.5 Pillow-3.0.0 SQLAlchemy-1.0.8 coverage-4.0.1 fake-factory-0.5.3 mock-1.3.0 mongoengine-0.9.0 pbr-1.8.1 pymongo-3.0.3 six-1.10.0 wheel-0.26.0
pip freeze
coverage==4.0.1
Django==1.8.5
fake-factory==0.5.3
mock==1.3.0
mongoengine==0.9.0
pbr==1.8.1
Pillow==3.0.0
pymongo==3.0.3
six==1.10.0
SQLAlchemy==1.0.8
wheel==0.26.0
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C examples test
cd flask_alchemy && PYTHONPATH=../.. python -m unittest
E
======================================================================
ERROR: test_demoapp (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: test_demoapp
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/Users/James/Documents/Work/Open Source/jamesbeith/factory_boy/examples/flask_alchemy/test_demoapp.py", line 5, in <module>
    import demoapp
  File "/Users/James/Documents/Work/Open Source/jamesbeith/factory_boy/examples/flask_alchemy/demoapp.py", line 22, in <module>
    from flask import Flask
ImportError: No module named 'flask'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
make[1]: *** [runtest-flask_alchemy] Error 1
make: *** [example-test] Error 2
```

**Comment by rbarrois** [comment]
Indeed, I just got bitten by this too.

Thanks for the report!
