### ISSUE TITLE
abstract inheritance

### ISSUE THREAD

**Issue by frague59** [rbarrois/factory_boy#242]
#201 

Hi, 

I've defined an `abstract` then a concrete Factory:
```
class PublishableFactory(DjangoModelFactory):
    class Meta:
        abstract = True
        model = 'intrautils.Publishable'

    state = factory.sequence(lambda x: get_random_state())
    author = 1
    date_publication = factory.sequence(lambda x: random_date(nullable=True))
    date_published_start = factory.sequence(lambda x: random_date(start=date_publication, nullable=True))
    date_published_end = factory.sequence(lambda x: random_date(start=date_published_start, nullable=True))
    priority = factory.sequence(lambda x: random.randint(1, 3))
    display_type = factory.Iterator(models.DisplayType.objects.all())

class EventFactory(PublishableFactory):
    class Meta:
        model = models.Event

    title = factory.sequence(lambda x: "Event %s" % get_title())
    content = factory.sequence(generate_content())
    location = factory.sequence(lambda x: random.choice(models.EventLocation.objects.all()))
    date_from = factory.sequence(lambda x: random_date())
    date_to = factory.sequence(lambda x: random_date(date_from, nullable=True))
``` 
, and I've the following issue :  
```
$ ./manage.py forge intrapubs.Event:10 --settings=intranet.settings.tests
intrapubs.foundry
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factoryboy_command/management/commands/forge.py", line 58, in handle
    self.autodiscover(limit_to=appnames)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factoryboy_command/management/commands/forge.py", line 44, in autodiscover
    foundry = import_module(path)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/utils/importlib.py", line 45, in import_module
    __import__(name)
  File "/home/fguerin/Boulot/workspace/django/intranet/src/intrapubs/foundry.py", line 102, in <module>
    class PublishableFactory(DjangoModelFactory):
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factory/base.py", line 123, in __new__
    base_factory=base_factory,
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factory/base.py", line 211, in contribute_to_class
    self.model = self.factory._load_model_class(self.model)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factory/django.py", line 127, in _load_model_class
    return get_model(app, model)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/factory/django.py", line 67, in get_model
    return _get_model(app, model)
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/fguerin/Boulot/workspace/django/intranet/virtualenv/lib/python2.7/site-packages/django/apps/config.py", line 162, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'intrautils' doesn't have a 'publishable' model.
```

Have you any idea on how to fix this ?

Thanks !

**Comment by rbarrois** [comment]
The problem here is that your factory is loaded before Django has finished loading.

Do you have a way to run through ``django.setup()`` *before* importing your ``foundry.py`` module?

**Comment by jeffwidman** [comment]
Closing, as this is Q&A rather than an actual issue with FactoryBoy. StackOverflow is probably a better place for Q"&A--if you do open a question there, feel free to post the link here and I'll take a look at it.
