### ISSUE TITLE
SelfAttribute doesn't detect attribute

### ISSUE THREAD

**Issue by ad-m** [rbarrois/factory_boy#255]
Hello,

I am would like to use custom field factory which reference another field of the object being constructed. I use factory inheritance too.

I defined custom field:
```python
def make_message(subject="Example subject",
                 from_addr="from@example.com",
                 to_addr="to@example.com",
                 text="Lorem ipsum"):
    msg = MIMEText(text)
    msg['Subject'] = subject
    msg['From'] = from_addr
    msg['To'] = to_addr
    return msg


class EmailField(factory.django.FileField):
    DEFAULT_FILENAME = 'example.eml'

    def _make_data(self, params):
        """Create data for the field."""
        return make_message(subject=params.get('subject', "Example subject"),
                            from_addr=params.get("from_addr", "from@example.com"),
                            to_addr=params.get("to_addr", "to@example.com"),
                            text=params.get("text", "Lorem ipsum")).as_string()
```
And 2 factories:
```python
class LetterFactory(factory.django.DjangoModelFactory):
    case = factory.SubFactory('foundation.cases.tests.factories.CaseFactory')
    subject = factory.Sequence(lambda n: 'letter-subject-/{0}/'.format(n))
    content = factory.Sequence(lambda n: 'letter-text-/{0}/'.format(n))

    class Meta:
        model = models.Letter
        abstract = True

class SendOutgoingLetterFactory(LetterFactory):
    sender_user = factory.LazyAttribute(lambda o: o.case.created_by)
    send_at = factory.LazyAttribute(lambda o: datetime.datetime.utcnow() +
                                    datetime.timedelta(hours=1))
    eml = EmailField(from_addr=factory.SelfAttribute('send_at'),
                     to_addr=factory.SelfAttribute('email.email'),
                     subject=factory.SelfAttribute('subject'),
                     text=factory.SelfAttribute('content'))
```

Unfortunately, I receive errors:
```
Traceback (most recent call last):
  File "/home/adas/Devel/foundation/foundation/letters/tests/test_models.py", line 8, in setUp
    self.object = SendOutgoingLetterFactory(subject="Example subj")
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 558, in create
    attrs = cls.attributes(create=True, extra=kwargs)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 400, in attributes
    force_sequence=force_sequence,
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 228, in build
    return stub.__fill__()
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 83, in __fill__
    res[attr] = getattr(self, attr)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 105, in __getattr__
    val = val.evaluate(self, self.__containers)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 160, in evaluate
    containers=containers,
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/declarations.py", line 298, in evaluate
    return self.generate(sequence, obj, create, defaults)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/django.py", line 208, in generate
    params = base.DictFactory.simple_generate(create, **params)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 645, in simple_generate
    return cls.generate(strategy, **kwargs)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 612, in generate
    return action(**kwargs)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 558, in create
    attrs = cls.attributes(create=True, extra=kwargs)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/base.py", line 400, in attributes
    force_sequence=force_sequence,
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 228, in build
    return stub.__fill__()
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 83, in __fill__
    res[attr] = getattr(self, attr)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 105, in __getattr__
    val = val.evaluate(self, self.__containers)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 160, in evaluate
    containers=containers,
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/declarations.py", line 140, in evaluate
    return deepgetattr(target, self.attribute_name, self.default)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/declarations.py", line 102, in deepgetattr
    return getattr(obj, name)
  File "/home/adas/.virtualenvs/foundation/local/lib/python2.7/site-packages/factory/containers.py", line 113, in __getattr__
    "definitions are %r." % (name, self.__values, self.__attrs))
AttributeError: The parameter content is unknown. Evaluated attributes are {}, definitions are {'text': <OrderedDeclarationWrapper for <SelfAttribute('content', default=<class 'factory.declarations._UNSPECIFIED'>)>>, 'from_addr': <OrderedDeclarationWrapper for <SelfAttribute('send_at', default=<class 'factory.declarations._UNSPECIFIED'>)>>, 'to_addr': <OrderedDeclarationWrapper for <SelfAttribute('email.email', default=<class 'factory.declarations._UNSPECIFIED'>)>>, 'subject': <OrderedDeclarationWrapper for <SelfAttribute('subject', default=<class 'factory.declarations._UNSPECIFIED'>)>>}.
```

If I commend out field ```eml``` which use ```factory.selfAttribute``` everything seems to work great:
```python
class SendOutgoingLetterFactory(LetterFactory):
    sender_user = factory.LazyAttribute(lambda o: o.case.created_by)
    send_at = factory.LazyAttribute(lambda o: datetime.datetime.utcnow() +
                                    datetime.timedelta(hours=1))
    #eml = EmailField(from_addr=factory.SelfAttribute('send_at'),
    #                 to_addr=factory.SelfAttribute('email.email'),
    #                 subject=factory.SelfAttribute('subject'),
    #                 text=factory.SelfAttribute('content'))
``` 

Do you have any idea? How  to use ```factory.SelfAttribute``` properly to pass to another field as attribute?

Greetings,

**Comment by rbarrois** [comment]
Hi — and sorry for the late reply :/

When you use a ``factory.declarations.ParameteredAttribute`` subclass (like ``factory.django.FileField``),
the "self" in ``factory.SelfAttribute`` refers to the attribute being built; in your example, that's the ``EmailField`` being constructed.

If you want to refer values from the containing factory, you should use ``SelfAttribute('..send_at')``: this instructs factory_boy to look at the ``send_at`` field of the parent context, i.e the ``SendOutgoingLetterFactory``.

Does this fix your issue?

**Comment by ad-m** [comment]
Thank you very much! Everything works fine now!

Here is my code if anybody will have similiar issue: https://github.com/pilnujemy/pytamy/blob/949a11d0d304753ff4139eb75f7b5f86b348b6c1/foundation/letters/tests/factories.py
