### ISSUE TITLE
float_to_decimal fails when FloatOperation trapped in Decimal context

### ISSUE THREAD

**Issue by dschien** [rbarrois/factory_boy#261]
Hi,

If I set 
`getcontext().traps[FloatOperation] = True`
then FuzzyDecimal fails because it does indeed convert a float directly to a decimal without first converting it to a string.

This is happening for Python 2.6 but not above.  Is there a reason for this? Or, am I misunderstanding something about the use of Decimals?

Many thanks

**Comment by rbarrois** [comment]
Hmm, I can't find a ``getcontext().traps[FloatOperation]`` in Python 2 docs: https://docs.python.org/2/library/decimal.html#signals

Regarding the difference between 2.6 and 2.7, the code is not exactly the same:
https://github.com/rbarrois/factory_boy/blob/master/factory/compat.py#L45


Do you have a more complete example?

**Comment by dschien** [comment]
It might be a python 3-only feature.
https://docs.python.org/3/library/decimal.html

Would that be a problem?

**Comment by rbarrois** [comment]
Well, it's because pre-2.7, calling ``decimal.Decimal(0.3)`` wasn't allowed.

Back to the issue you have: can you provide an example of what fails?
From what you've said, I understand that you get a failure with code similar to the one below; is that the case?

```python
import decimal
import factory
import factory.fuzzy

class Foo(object):
    def __init__(self, dec):
        self.dec = dec

class FooFactory(factory.Factory):
    dec = factory.fuzzy.FuzzyDecimal(0, 10)

    class Meta:
        model = Foo

decimal.getcontext().traps[decimal.FloatOperation] = True
FooFactory()
```

**Comment by dschien** [comment]
Correct. Thanks for creating this minimal setup.
If I run this, I get the following error:

```
Traceback (most recent call last):
  File "/Users/abcde/workspaces/python/test.py", line 19, in <module>
    FooFactory()
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/base.py", line 81, in __call__
    return cls.create(**kwargs)
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/base.py", line 566, in create
    attrs = cls.attributes(create=True, extra=kwargs)
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/base.py", line 401, in attributes
    force_sequence=force_sequence,
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/containers.py", line 228, in build
    return stub.__fill__()
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/containers.py", line 83, in __fill__
    res[attr] = getattr(self, attr)
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/containers.py", line 105, in __getattr__
    val = val.evaluate(self, self.__containers)
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/containers.py", line 160, in evaluate
    containers=containers,
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/fuzzy.py", line 66, in evaluate
    return self.fuzz()
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/fuzzy.py", line 167, in fuzz
    base = compat.float_to_decimal(_random.uniform(self.low, self.high))
  File "/Users/abcde/.virtualenvs/py35/lib/python3.5/site-packages/factory/compat.py", line 50, in float_to_decimal
    return decimal.Decimal(fl)
decimal.FloatOperation: [<class 'decimal.FloatOperation'>]

Process finished with exit code 1
```

As you can see, I am running python 3.5.

**Comment by rbarrois** [comment]
Hmm, I don't understand your issue anymore :(

You reported a problem with "trapping decimal operations in 2.6" but now you say it's happening on 3.5 instead?
I'm a bit confused, could you explain again what you tried to do, under which Python version, and which failure you encountered?

**Comment by dschien** [comment]
Oh sorry for confusion.  What I meant is that the conversion of floats to strings prior to decimals is happening for python 2.6, just as you were pointing out with the link to 
https://github.com/rbarrois/factory_boy/blob/master/factory/compat.py#L45

What I suggest is to do this generally for all versions of python, including 3.5 were I am at. This would solve the problem. However, it depends on what you intended with not doing this for 2.7.

Many thanks
