### ISSUE TITLE
SQLAlchemy model primary key column attribute name must match column name

### ISSUE THREAD

**Issue by hartror** [rbarrois/factory_boy#78]
So we've got a set of SQLAlchemy models like so (don't ask why, it makes me sad).

```python
class Test(Base):
    __tablename__ = "test"
    
    id = sqlalchemy.Column('id_', sqlalchemy.Integer, primary_key=True)
```

When using a factory for the class we get:

```
Traceback (most recent call last):
  File "<pyshell#0>", line 16, in <module>
    TestFactory.build()
  File "/usr/local/lib/python2.7/dist-packages/factory/base.py", line 434, in build
    attrs = cls.attributes(create=False, extra=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/factory/base.py", line 316, in attributes
    force_sequence=force_sequence,
  File "/usr/local/lib/python2.7/dist-packages/factory/containers.py", line 263, in build
    sequence = self.factory._generate_next_sequence()
  File "/usr/local/lib/python2.7/dist-packages/factory/base.py", line 287, in _generate_next_sequence
    cls._next_sequence = cls._setup_next_sequence()
  File "/usr/local/lib/python2.7/dist-packages/factory/alchemy.py", line 37, in _setup_next_sequence
    pk = getattr(model, model.__mapper__.primary_key[0].name)
AttributeError: type object 'Test' has no attribute 'id_'
```

A full example:

```python
from sqlalchemy.ext.declarative import declarative_base
import sqlalchemy
import factory.alchemy

Base = declarative_base()

class Test(Base):
    __tablename__ = "test"
    
    id = sqlalchemy.Column('id_', sqlalchemy.Integer, primary_key=True)

class TestFactory(factory.alchemy.SQLAlchemyModelFactory):
    FACTORY_FOR = Test
    FACTORY_SESSION = None

TestFactory.build()
```

**Comment by rbarrois** [comment]
This issue has been fixed in 13d310f, and will be part of the 2.5.0 release.
